# Site variables
name: Fahien
description: a heap of bits

footer-links:
    github: Fahien
    twitter: Fahien
    linkedin: antoniocaggiano
    youtube: c/AntonioCaggiano
    rss: 42

# Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-68855324-1
    
# Configuration
permalink: /:year/:month/:day/:title/
version: v1.2.0

kramdown:
    input: GFM
    syntax_highlighter: rouge
    syntax_highlighter_opts:
        css_class: 'highlight'

sass:
    style: :expanded

gems:
    - jekyll-sitemap
    - jekyll-feed

exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
